name: Docker

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
  push:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo '${{ secrets.QUAY_IO }}' | docker login --username 'hakuyume+github_actions_rust_musl' --password-stdin quay.io
      - run: make push
